import os

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate

os.makedirs("sample_docs", exist_ok=True)

def create_company_policy_pdf():
    pdf_path = "sample_docs/company_policy.pdf"
    doc = SimpleDocTemplate(pdf_path, pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=72)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=22,
        spaceAfter=15,
        textColor="#1a365d"
    )
    
    heading_style = ParagraphStyle(
        'HeadingStyle',
        parent=styles['Heading2'],
        fontSize=14,
        spaceBefore=12,
        spaceAfter=6,
        textColor="#2b6cb0"
    )
    
    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        spaceAfter=8
    )

    story.append(Paragraph("Acme Corp Employee Handbook & Policies", title_style))
    story.append(Paragraph("Section 1: Remote Work Policy", heading_style))
    story.append(Paragraph("Acme Corp supports flexible working arrangements. Employees may work remotely up to 3 days per week with manager approval. Core working hours are 10:00 AM to 4:00 PM local time, during which employees must be available for communication via Slack and email.", body_style))
    
    story.append(Paragraph("Section 2: Travel & Expense Reimbursement", heading_style))
    story.append(Paragraph("All business travel must be pre-approved by a department head. Economy flights are mandatory for domestic flights under 6 hours. Hotel rates should not exceed $250 per night. Expense reports must be submitted within 14 days of trip completion along with itemized receipts.", body_style))
    
    story.append(Paragraph("Section 3: Information Security", heading_style))
    story.append(Paragraph("Employees must use company-approved password managers and enable Multi-Factor Authentication (MFA) on all corporate accounts. Sharing credentials or storing unencrypted API keys in public repositories is strictly prohibited and subject to disciplinary action.", body_style))
    
    doc.build(story)
    print(f"Created {pdf_path}")

def create_project_spec_pdf():
    pdf_path = "sample_docs/project_spec.pdf"
    doc = SimpleDocTemplate(pdf_path, pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=72)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=22,
        spaceAfter=15,
        textColor="#2c5282"
    )
    
    heading_style = ParagraphStyle(
        'HeadingStyle',
        parent=styles['Heading2'],
        fontSize=14,
        spaceBefore=12,
        spaceAfter=6,
        textColor="#2b6cb0"
    )
    
    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        spaceAfter=8
    )

    story.append(Paragraph("Project Artemis: AI Document Q&A Technical Specification", title_style))
    story.append(Paragraph("Section 1: Architecture Overview", heading_style))
    story.append(Paragraph("Project Artemis is a Retrieval-Augmented Generation (RAG) system designed to process PDF documents and answer user queries with precise citations. The system utilizes Chroma DB as the vector store, sentence-transformers for local embedding generation, and supports both local Ollama (Gemma model) and cloud Gemini API as LLM backends.", body_style))
    
    story.append(Paragraph("Section 2: Data Ingestion Pipeline", heading_style))
    story.append(Paragraph("Documents are loaded using PyPDFLoader, split into overlapping chunks of 1000 characters with a 200-character overlap using RecursiveCharacterTextSplitter. Chunks are embedded into 384-dimensional vectors and indexed in Chroma with metadata tracking source filename and page number.", body_style))
    
    story.append(Paragraph("Section 3: Evaluation & Citations", heading_style))
    story.append(Paragraph("Every response generated by Project Artemis includes explicit citations indicating the source document name and page number. Retrieved context chunks are displayed in the user interface to ensure hallucination reduction and answer verifiability.", body_style))
    
    doc.build(story)
    print(f"Created {pdf_path}")

if __name__ == "__main__":
    create_company_policy_pdf()
    create_project_spec_pdf()
